// lib/main.dart
import 'package:flutter/material.dart';
import 'screens/home_screen.dart';
import 'screens/game_screen.dart';
import 'screens/teamselection_screen.dart';
import 'screens/gamemode_screen.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';
import 'screens/anonymous_login_screen.dart';
import 'screens/connection_screen.dart';
import 'screens/online_game_screen.dart';
// generated by flutterfire configure

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    print("Firebase initialized successfully");
  } catch (e) {
    print("Firebase initialization error: $e");
  }

  runApp(const TestGame());
}

class TestGame extends StatelessWidget {
  const TestGame({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Test Game', // Changed app title here
      initialRoute: '/',
      routes: {
        //
        '/': (context) => const HomeScreen(),
        '/mode': (context) => const GameModeScreen(),
        '/game': (context) => const GameScreen(),
        '/select': (context) => const TeamSelectionScreen(),
        '/login': (context) => const AnonymousLoginScreen(),
        '/connect': (context) => const ConnectingScreen(),

        '/ongame': (context) => const OnlineGameScreen(),
      },
    );
  }
}
